YMLParser/Controllers/UserSelectionsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using YMLParser.Models;

namespace YMLParser.Controllers
{
    [Authorize]
    public class UserSelectionsController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        private void CreateUserSelection()
        {
            try
            {
                if (CurrentUser != null)
                {
                    CurrentUserSelection = new UserSelection
                    {
                        UserId = CurrentUser.Id,
                        AddedProviders = new List<Provider>(),
                        ExistingLinks = new List<OutputLink>()
                    };
                    _db.UserSelections.Add(CurrentUserSelection);
                    _db.SaveChanges();
                }
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        Trace.TraceInformation("Property: {0} Error: {1}",
                            validationError.PropertyName,
                            validationError.ErrorMessage);
                    }
                }
            }
        }

        private void GetCurrentUserInfo()
        {
            if (User.Identity.IsAuthenticated)
            {
                UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                CurrentUser = UserManager.FindById(User.Identity.GetUserId());
            }
        }

        private void GetUserSelection()
        {
            CurrentUserSelection = _db.UserSelections.First(s => s.UserId == CurrentUser.Id);
            var providers = _db.Providers.Include(p => p.UserSelections);
            var links = _db.OutputLinks.Include(p => p.UserSelection);

            ViewBag.Providers = providers.ToList();
            ViewBag.Links = CurrentUserSelection.ExistingLinks.ToList();
            ViewBag.Link = links.ToList();
        }

        private bool UserSelectionExists()
        {
            if (CurrentUser != null && _db.UserSelections.Any(s => s.UserId == CurrentUser.Id))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        private ApplicationUser CurrentUser { get; set; }
        private UserSelection CurrentUserSelection { get; set; }

        private ApplicationUserManager UserManager { get; set; }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        // POST: UserSelections/add
        [HttpPost]
        public ActionResult Add()
        {
            return PartialView("Create");
        }

        // POST: UserSelections/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Provider provider)
        {
            GetCurrentUserInfo();
            GetUserSelection();

            if (ModelState.IsValid)
            {
                provider.Link = provider.Link.Trim();

                Provider newProvider;
                //пробиваем поставщика по базе
                if (_db.Providers.Any(p => p.Link == provider.Link))//если встречается в БД
                {
                    newProvider = await _db.Providers.FirstOrDefaultAsync(p => p.Link == provider.Link);
                    if (!newProvider.UserSelections.Contains(CurrentUserSelection))
                    {
                        newProvider.UserSelections.Add(CurrentUserSelection);
                        CurrentUserSelection.AddedProviders.Add(newProvider);
                        _db.Entry(newProvider).State = EntityState.Modified;
                        _db.Entry(CurrentUserSelection).State = EntityState.Modified;
                        _db.SaveChanges();
                    }
                }
                else //если нет
                {
                    newProvider = provider;
                    _db.Providers.Add(newProvider);
                    _db.SaveChanges();

                    //запускаем парсер
                    Parser parser = new Parser(_db);
                    //получаем физический файл
                    var output = await parser.ParseInitialFile(provider.Link);
                    if (output == null)
                    {
                        _db.Providers.Remove(newProvider);
                        _db.Entry(provider).State = EntityState.Deleted;
                        _db.SaveChanges();
                        return Content("Ссылка на XML не верна!");
                    }
                    newProvider.Name = output.Vendor;
                    newProvider.MainOutputFile = output;
                    newProvider.UserSelections.Add(CurrentUserSelection);

                    //парсим полученные из файла категории и добавляем их куда надо
                    parser.ParseAllCategories(output.Categories.Values.ToList(), newProvider);

                    CurrentUserSelection.AddedProviders.Add(newProvider);
                    _db.Entry(CurrentUserSelection).State = EntityState.Modified;
                    _db.Entry(newProvider).State = EntityState.Modified;
                    _db.SaveChanges();
                }
            }

            return RedirectToAction("Index", CurrentUserSelection);
        }

        //// GET: UserSelections/Edit/5
        //public async Task<ActionResult> EditProvider(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Provider provider = CurrentUserSelection.AddedProviders.First(p => p.Id == id);
        //    UserSelection userSelection = await db.UserSelections.FindAsync(id);
        //    if (userSelection == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userSelection);
        //}


        //// POST: UserSelections/Edit/5
        //// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        //// сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "Id,UserId")] UserSelection userSelection)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(userSelection).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    return View(userSelection);
        //}

        // GET: UserSelections/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            GetCurrentUserInfo();
            GetUserSelection();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CurrentUserSelection == null)
            {
                return HttpNotFound();
            }
            Provider provider = CurrentUserSelection.AddedProviders.First(p => p.Id == id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: UserSelections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            GetCurrentUserInfo();
            GetUserSelection();

            Provider provider = await _db.Providers.FindAsync(id);

            CurrentUserSelection.AddedProviders.Remove(provider);
            provider.UserSelections.Remove(CurrentUserSelection);
            //удаляем поставщика если больше никем не используется
            if (provider.UserSelections.Count < 1)
            {
                _db.Entry(provider).State = EntityState.Deleted;
                var remove = _db.OutputFiles.Where(f => f.Vendor == provider.Name);
                _db.OutputFiles.RemoveRange(remove);
            }
            else
            {
                _db.Entry(provider).State = EntityState.Modified;
            }

            _db.Entry(CurrentUserSelection).State = EntityState.Modified;
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: UserSelections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            GetCurrentUserInfo();
            GetUserSelection();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CurrentUserSelection == null)
            {
                return HttpNotFound();
            }
            Provider provider = _db.Providers.Include(p => p.Categories).FirstOrDefault(p => p.Id == id);
            if (provider == null || !provider.UserSelections.Contains(CurrentUserSelection))
            {
                return HttpNotFound();
            }
            ViewBag.Categories = provider.Categories.ToList();

YMLParser/Views/UserSelections/Create.cshtml
@model YMLParser.Models.Provider

<h3>Добавить поставщика</h3>

@using (Html.BeginForm("Create", "UserSelections")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

YMLParser/Views/UserSelections/Delete.cshtml
@model YMLParser.Models.Provider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удалить поставщика</h2>

<h3>Вы уверены что хотите удалить этого поставщика?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

YMLParser/Views/UserSelections/Details.cshtml
@using YMLParser.Models
@model YMLParser.Models.Provider

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserSelection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

    </dl>
    @Html.ActionLink("Посмотреть файл", "GetFile", new {id = Model.MainOutputFile_Id}, new {@class = "btn btn-primary"})
    <h4>
        @Html.DisplayNameFor(model => model.Categories)
    </h4>
    <div>
        <ul>
        @foreach (Category category in ViewBag.Categories)
        {
            <li class="col-md-4">
                @category.Name;
            </li>
        }
        </ul>
    </div>
</div>
<p>
    @*@Html.ActionLink("Правка", "EditProvider", new { id = Model.Id }) |*@
    @Html.ActionLink("Назад", "Index")
</p>

YMLParser/Views/UserSelections/Edit.cshtml
@model YMLParser.Models.UserSelection

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSelection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

YMLParser/Views/UserSelections/Index.cshtml
@model YMLParser.Models.UserSelection

@{
    ViewBag.Title = "Поставщики";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Сформировать XML</h2>

@using (Ajax.BeginForm("Add", new AjaxOptions{UpdateTargetId = "createNew" }))
{
    @Html.AntiForgeryToken() 
    <input id="createButton" class ="btn btn-primary" type="submit" value="+ Добавить поставщика" style="margin-top: 10px;"/>
}
@*@Html.ActionLink("+ Добавить поставщика", "Create")*@

<div class="col-md-12", id="createNew">
</div>

<div class="panel panel-info">
  <div class="panel-heading">
      <a class="btn-block" data-toggle="collapse" href="#collapseProviders" aria-expanded="true" aria-controls="collapseProviders" style="text-align: left">
          Поставщики
      </a>
  </div>
  <div class="panel-body" style="padding: 0;">
      <div class="in" id="collapseProviders">
          <div class="table-wrapper">
              @if (Model.AddedProviders.Count > 0)
              {
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.AddedProviders.FirstOrDefault().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AddedProviders.FirstOrDefault().Link)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.AddedProviders)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Link)
                            </td>
                            <td>
                                @*@Html.ActionLink("Правка", "Edit", new { id=item.Id }) |*@
                                @Html.ActionLink("Подробно", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                    }
                </table>
              }
              else
              {
                <p class="text-center empty-panel-text">Пусто...</p>
              }
              
          </div>
      </div>
    </div>
</div>

<a class="btn btn-primary" href="@Url.Action("Create","OutputLinks")" >
    Сформировать XML
</a>

<div class="panel panel-info">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" href="#collapseLinks" aria-expanded="true" aria-controls="collapseLinks" style="text-align: left">
            Ссылки
        </a>
    </div>
    <div class="panel-body" style="padding: 0;">
        <div class="in" id="collapseLinks">
            <div class="table-wrapper">
                @if (Model.ExistingLinks.Count > 0)
                {
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ExistingLinks.FirstOrDefault().Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ExistingLinks.FirstOrDefault().Link)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model.ExistingLinks)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Link)
                                </td>
                                <td>
                                    @*@Html.ActionLink("Правка", "Edit", new { id=item.Id }) |*@
                                    @Html.ActionLink("Подробно", "Details","OutputLinks", new {id = item.Id}, null) |
                                    @Html.ActionLink("Удалить", "Delete", "OutputLinks", new {id = item.Id}, null)
                                </td>
                            </tr>
                        }

                    </table>
                }
                else
                {
                    <p class="text-center empty-panel-text">Пусто...</p>
                }
                
            </div>
        </div>
    </div>
</div>